
# With a postgres database
# database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=reviewboard
#       - POSTGRES_PASSWORD=reviewboard
#    volumes:
#         - /home/reviewboard/database:/var/lib/postgresql/data

#database:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=reviewboard
#      - MYSQL_USER=reviewboard
#      - MYSQL_PASSWORD=reviewboard
#      - MYSQL_DATABASE=reviewboard
#   volumes:
#        - /home/reviewboard/database:/var/lib/mysql

database:
    image: postgres
    environment:
       - POSTGRES_USER=reviewboard
       - POSTGRES_PASSWORD=reviewboard
    volumes:
       - postgresql-data:/var/lib/postgresql/data

cache:
    image: memcached

reviewboard:
    image: ducatel/reviewboard
    environment:
       - DB_TYPE=postgresql
       - DB_PORT=5432
    links:
        - "cache:memcached"
        - "database:rb_db"
    ports:
        - "8000:8000"
    volumes:
        - media-data:/media